name: pipeline
on: 
    push:
        branches: 
            - main
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: "Use cache"
                default: true

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3.5.1
              with:
                    node-version: '22.x'
                    cache: 'npm'
                    cache-dependency-path: angular-app/package-lock.json

            - name: Cache dependencies
              uses: actions/cache@v4
              id: cache
              with:
                path: angular-app/node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                        ${{ runner.os }}-node-modules-

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Run tests
              run: npm run test -- --watch=false --browsers=ChromeHeadless

            - name: Build Angular app
              run: npm run build -- --configuration=production

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: angular-app-build
                path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                   name: angular-app-build
                   path: dist

            - name: Show directory structure
              run: ls -lrt angular-app/dist
